name: "Mikail Khona's Blog"
author:
  name: "Mikail Khona"
  email: "mikailkhona@gmail.com"
  twitter: "KhonaMikail"
gems:
  - jekyll-feed
title: "Mikail Khona"
description: ""
logo: content/gridcellmodules.png
show_downloads: false
google_analytics: UA-94033137-1
theme: jekyll-theme-minimal
markdown: kramdown
kramdown:
  math_engine: mathjax
collections_dir: collections
collections:
  blog_posts:
    output: true
  blog_drafts:
    output: true
  own_research:
    output: true


